mail-parser:
  target-dir: /Users/antonchernyavskiy/IdeaProjects/mail-parser/src/main/resources/remote/
  target-strings: date-time,client-ip,client-hostname,server-ip,server-hostname,source-context,connector-id,source,event-id,internal-message-id,message-id,network-message-id,recipient-address,recipient-status,total-bytes,recipient-count,related-recipient-address,reference,message-subject,sender-address,return-path,message-info,directionality,tenant-id,original-client-ip,original-server-ip,custom-data,transport-traffic-type,log-id,schema-version
  filtered-strings: client-ip,client-hostname
  split-char: ","
  prefix-fields-to-trim: "#Fields: "